# Generated by Django 4.2.4 on 2023-08-19 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos_humanos', '0001_initial'),
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcliente',
            name='registrado_por',
            field=models.ForeignKey(db_column='registrado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='username',
            field=models.OneToOneField(db_column='username', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
