# Generated by Django 4.2.4 on 2023-08-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('recursos_humanos', '0001_initial'),
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDevolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_devolucion', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.tbcliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
            ],
            options={
                'db_table': 'tb_devolucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbFacturaCliente',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado_pago', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.tbcliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
            ],
            options={
                'db_table': 'tb_factura_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbVentas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_de_registro', models.DateTimeField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tbfacturacliente')),
            ],
            options={
                'db_table': 'tb_ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbInventario',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bodega.tblibros')),
                ('nombre', models.CharField(max_length=45)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edicion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
                ('id_devolucion', models.ForeignKey(blank=True, db_column='id_devolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tbdevolucion')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.tbpedidos')),
            ],
            options={
                'db_table': 'tb_inventario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tbdevolucion',
            name='id_factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tbfacturacliente'),
        ),
        migrations.AddField(
            model_name='tbdevolucion',
            name='id_libro',
            field=models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.tblibros'),
        ),
        migrations.AlterUniqueTogether(
            name='tbdevolucion',
            unique_together={('id_devolucion', 'id_libro')},
        ),
        migrations.CreateModel(
            name='TbLibrosxventas',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='lixv_venta', serialize=False, to='ventas.tbventas')),
                ('cantidad', models.IntegerField()),
                ('valor_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lixv_libro', to='bodega.tblibros')),
            ],
            options={
                'db_table': 'tb_librosxventas',
                'managed': True,
                'unique_together': {('id_venta', 'id_libro')},
            },
        ),
    ]
