# Generated by Django 4.2.4 on 2023-08-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodega', '0001_initial'),
        ('cliente', '0001_initial'),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbFacturaCliente',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('estado_pago', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.tbcliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
            ],
            options={
                'verbose_name': 'Factura Cliente',
                'verbose_name_plural': 'Facturas Cliente',
                'db_table': 'tb_factura_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbVentas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_de_registro', models.DateTimeField()),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tbfacturacliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'tb_ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbDevolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_devolucion', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.tbcliente')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='recursos_humanos.tbempleado')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tbfacturacliente')),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='bodega.tblibros')),
            ],
            options={
                'verbose_name': 'Devolucion',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'tb_devolucion',
                'managed': True,
                'unique_together': {('id_devolucion', 'id_libro')},
            },
        ),
        migrations.CreateModel(
            name='TbLibrosxventas',
            fields=[
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='lixv_venta', serialize=False, to='ventas.tbventas')),
                ('cantidad', models.IntegerField()),
                ('valor_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, related_name='lixv_libro', to='bodega.tblibros')),
            ],
            options={
                'verbose_name': 'Libro - Venta',
                'verbose_name_plural': 'Libros - Ventas',
                'db_table': 'tb_librosxventas',
                'managed': True,
                'unique_together': {('id_venta', 'id_libro')},
            },
        ),
    ]
