# Generated by Django 4.2.4 on 2023-08-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbFacturaProveedor',
            fields=[
                ('id_factura_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_factura_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbPagos',
            fields=[
                ('id_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=20)),
                ('estado_pago', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbSalarios',
            fields=[
                ('id_salario', models.AutoField(primary_key=True, serialize=False)),
                ('salario_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ihss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infop', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_neto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tb_salarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbServicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tb_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbPagosxpedidos',
            fields=[
                ('id_pago', models.OneToOneField(db_column='id_pago', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='finanzas.tbpagos')),
            ],
            options={
                'db_table': 'tb_pagosxpedidos',
                'managed': True,
            },
        ),
    ]
