# Generated by Django 4.2.4 on 2023-08-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField()),
                ('ultima_compra', models.DateTimeField()),
                ('monto_total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, default='clientes/clientes_empty.png', null=True, upload_to='clientes', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tb_cliente',
                'managed': True,
            },
        ),
    ]
