# Generated by Django 4.2.4 on 2023-08-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAutor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Autor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True, verbose_name='F. Nac')),
                ('ciudad_origen', models.CharField(blank=True, max_length=50, null=True, verbose_name='C. Origen')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'tb_autor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbCategoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'tb_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbCategoriaxlibro',
            fields=[
                ('id_libxcat', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Categoria-Libro',
                'verbose_name_plural': 'Categorias-Libros',
                'db_table': 'tb_categoriaxlibro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEditorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('sitio_web', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'tb_Editorial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbLibros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Libro')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('sipnosis', models.TextField(blank=True, max_length=200, null=True, verbose_name='Sipnosis')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], max_length=20, verbose_name='Disponibilidad')),
                ('edicion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edicion')),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='libros', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'tb_libros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbPedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_factura_proveedor', models.IntegerField()),
                ('fecha_solicitado', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('Cancelada', 'Cancelada'), ('procesando', 'Procesando'), ('completada', 'Completada')], default='Pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], default='Efectivo', max_length=20)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'tb_pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbProveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=20, unique=True, verbose_name='Telefono')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('sitio_web', models.CharField(max_length=50, unique=True, verbose_name='Sitio Web')),
                ('inicio_contrato', models.DateTimeField(verbose_name='Inicio Contrato')),
                ('fin_contrato', models.DateTimeField(verbose_name='Fin Contrato')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'tb_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEditorialxproveedor',
            fields=[
                ('id_proveedor', models.OneToOneField(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bodega.tbproveedor')),
            ],
            options={
                'verbose_name': 'Editorial-Proveedor',
                'verbose_name_plural': 'Editorial-Proveedor',
                'db_table': 'tb_editorialxproveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbInventario',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bodega.tblibros')),
                ('nombre', models.CharField(max_length=45)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edicion', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbLibroxpedido',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bodega.tblibros')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Libro-Pedido',
                'verbose_name_plural': 'Libro-Pedido',
                'db_table': 'tb_libroxpedido',
            },
        ),
        migrations.CreateModel(
            name='TbLibroxproveedor',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bodega.tblibros')),
            ],
            options={
                'verbose_name': 'Libro-Proveedor',
                'verbose_name_plural': 'Libro-Proveedor',
                'db_table': 'tb_libroxproveedor',
                'managed': True,
            },
        ),
    ]
